# Generated by Django 5.2.1 on 2025-05-25 00:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place', models.CharField(help_text='Ingrese el nombre de la faena', max_length=200, verbose_name='Nombre de Faena')),
                ('contract_number', models.ImageField(help_text='Ingrese número de contrato si corresponde', max_length=20, unique=True, upload_to='', verbose_name='número de contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('id_card', models.CharField(max_length=10, verbose_name='Cédula de identidad')),
                ('birth_date', models.DateField(verbose_name='Fecha Nacimiento')),
                ('adress', models.CharField(help_text='Dirección del trabajador', max_length=200, verbose_name='Dirección')),
                ('children', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Cantidad de hijos')),
                ('picture', models.ImageField(upload_to='upload/%d%m%Y')),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.workplace', verbose_name='Lugar de Trabajo')),
            ],
        ),
    ]
