# Generated by Django 5.2.1 on 2025-05-25 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='workplace',
            name='contract_number',
            field=models.IntegerField(help_text='Ingrese número de contrato si corresponde', unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='número de contrato'),
        ),
    ]
