# Generated by Django 5.2.1 on 2025-05-25 00:47

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_adress_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mail',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CL', unique=True, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_card',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cédula de identidad'),
        ),
    ]
