# Generated by Django 5.2.1 on 2025-05-25 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_mail_employee_phone_alter_employee_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_number',
            field=models.IntegerField(default=1, editable=False, verbose_name='Número de contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='entry_date',
            field=models.DateField(default='2025-02-19', verbose_name='Fecha de Ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.workplace', verbose_name='Lugar de Trabajo'),
        ),
    ]
