# Generated by Django 5.2.1 on 2025-05-25 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_contract_number_employee_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Desvinculado', 'Desvinculado')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_number',
            field=models.IntegerField(verbose_name='Número de contrato'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='contract_number',
            field=models.IntegerField(help_text='Ingrese número de contrato si corresponde', unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='número de contrato'),
        ),
    ]
