# Generated by Django 5.2.1 on 2025-05-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_status_alter_employee_contract_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Salida'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reason_for_leaving',
            field=models.CharField(blank=True, choices=[('Renuncia', 'Renuncia voluntaria'), ('Termino_del_Plazo', 'Término de contrato'), ('Necesidades_empresa', 'Despido por necesidades de la empresa'), ('Abandono', 'Abandono del trabajo'), ('Inc_Grave', 'Despido por incumplimiento grave'), ('Mutuo_Acuerdo', 'Mutuo acuerdo'), ('Muerte', 'Muerte del trabajador'), ('Jubilado', 'Jubilación')], max_length=30, null=True, verbose_name='Motivo de salida'),
        ),
    ]
