# Generated by Django 5.2.1 on 2025-05-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_end_date_employee_reason_for_leaving'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('Plazo_Fijo', 'Plazo Fijo'), ('Indefinido', 'Indefinido')], default='Indefinido', verbose_name='Tipo de Contrato'),
            preserve_default=False,
        ),
    ]
