# Generated by Django 5.2.1 on 2025-05-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.TextField(default='Calama', help_text='Ciudad del trabajador', verbose_name='Ciudad'),
            preserve_default=False,
        ),
    ]
