# Generated by Django 5.2.1 on 2025-05-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=42, verbose_name='Edad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(help_text='Ciudad del trabajador', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Desvinculado', 'Desvinculado')], verbose_name='Estado'),
        ),
    ]
