# Generated by Django 5.2.1 on 2025-05-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_age_alter_employee_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(editable=False, verbose_name='Edad'),
        ),
    ]
