# Generated by Django 5.2.1 on 2025-05-25 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Cargo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Trabajadores 2', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Desvinculado', 'Desvinculado'), ('En_Proceso', 'En Proceso de Contratación')], verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.position'),
        ),
    ]
