# Generated by Django 5.2.1 on 2025-05-25 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_position_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'Centro de Trabajo', 'verbose_name_plural': 'Centros de Trabajo'},
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('casado', 'Casado'), ('soltero', 'Soltero'), ('separado', 'Separado'), ('viudo', 'Viudo')], null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Cargo'),
        ),
    ]
