# Generated by Django 5.2.1 on 2025-05-25 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='contract_number',
            field=models.IntegerField(blank=True, help_text='Ingrese número de contrato si corresponde', null=True, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='número de contrato'),
        ),
    ]
