# Generated by Django 5.2.1 on 2025-05-31 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_workplace_contract_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Sin estudios'), (2, 'Básica incompleta'), (3, 'Básica completa'), (4, 'Media incompleta'), (5, 'Media completa'), (6, 'Técnica incompleta'), (7, 'Técnica completa'), (8, 'Universitaria incompleta'), (9, 'Universitaria completa'), (10, 'Postgrado')], unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nivel educacional')),
                ('years_study', models.PositiveSmallIntegerField(verbose_name='Años de estudio promedio')),
            ],
            options={
                'verbose_name': 'Nivel Educacional',
                'verbose_name_plural': 'Niveles Educacionales',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('separado', 'Separado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_civil', 'Unión Civil')], null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.region', verbose_name='Región de origen'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ciudad/Comuna')),
                ('is_capital', models.BooleanField(default=False, verbose_name='Es capital regional')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Población')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['region', 'name'],
                'unique_together': {('name', 'region')},
            },
        ),
    ]
