# Generated by Django 5.2.1 on 2025-06-10 17:21

import django.db.models.deletion
import phonenumber_field.modelfields
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employee_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contacto_emergencia',
            field=models.CharField(blank=True, help_text='En caso de emergencia, llamar a:', max_length=100, null=True, verbose_name='nombre contacto emergencia:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='numero_emergencia',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Teléfono emergencia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='employees.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
