# Generated by Django 5.2.1 on 2025-06-10 17:44

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employee_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='boss',
            field=models.BooleanField(default=1, verbose_name='Es jefatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='adc',
            field=models.CharField(default=1, max_length=150, verbose_name='Nombre ADC o líder del contrato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_number',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='work_place', chained_model_field='work_place', on_delete=django.db.models.deletion.CASCADE, sort='True', to='employees.workplace', verbose_name='Número de contrato'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Cargo'),
            preserve_default=False,
        ),
    ]
