# Generated by Django 5.2.1 on 2026-07-16 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.DeleteModel(
            name='EducationLevel',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='region',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_place',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'name'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='boss',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='children',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='numero_emergencia',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reason_for_leaving',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_consent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de autorización'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_consent_revoked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de retiro de autorización'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, help_text='El trabajador autoriza recibir notificaciones cuando se publiquen nuevos contenidos en el portal.', verbose_name='Autoriza notificaciones por correo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_card',
            field=models.CharField(help_text='Ejemplo: 12.345.678-9', max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='WorkPlace',
        ),
    ]
