# Generated by Django 5.2.1 on 2026-07-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_alter_city_unique_together_remove_city_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Debe cambiar su contraseña'),
        ),
    ]
