# Generated by Django 5.2.1 on 2025-05-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blog_blog_body_alter_blog_author_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado')], default='Borrador', verbose_name='Estado'),
        ),
    ]
