# Generated by Django 5.2.1 on 2026-07-16 22:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido'),
        ),
    ]
