# Generated by Django 5.2.1 on 2026-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_blog_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='notification_sent',
            field=models.BooleanField(default=False, editable=False, verbose_name='Notificación enviada'),
        ),
    ]
